/**
 * Memory index management.
 *
 * Manages the memory index file (MEMORY.md) with type constraints
 * and size limits. Adapted from Claude Code's memdir.ts.
 */

import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { createSubsystemLogger } from "../logging/subsystem.js";
import {
  MAX_MEMORY_INDEX_BYTES,
  MAX_MEMORY_INDEX_LINES,
  MAX_MEMORY_SUMMARY_CHARS,
  MEMORY_TYPES,
  type MemoryEntry,
  type MemoryIndexFile,
  type MemoryTruncationResult,
  type MemoryType,
} from "./memory-types.js";

const log = createSubsystemLogger("memory/index");

// ============================================================================
// Constants
// ============================================================================

const MEMORY_HEADER = `# Memory Index

> This file contains structured memory entries for context preservation.
> Memories are classified by type: user, feedback, project, reference.
> Generated by OpenClaw memory system.

`;

// ============================================================================
// Memory Index Parser
// ============================================================================

/**
 * Parse a memory entry from markdown format.
 */
export function parseMemoryEntry(line: string): MemoryEntry | undefined {
  // Format: `- [type] summary (id, createdAt, source)`
  const match = line.match(/^-\s+\[([^\]]+)\]\s+(.+)\s+\(([^,]+),\s*([^,]+)(?:,\s*([^)]+))?\)$/);
  if (!match) {
    return undefined;
  }

  const type = match[1] as MemoryType;
  const summary = match[2];
  const id = match[3];
  const createdAt = parseInt(match[4], 10);
  const source = match[5]?.trim() || undefined;

  if (!MEMORY_TYPES.includes(type)) {
    log.warn(`Invalid memory type: ${type}`);
    return undefined;
  }

  return {
    id,
    type,
    summary,
    createdAt,
    source,
  };
}

/**
 * Format a memory entry to markdown.
 */
export function formatMemoryEntry(entry: MemoryEntry): string {
  const truncatedSummary = truncateSummary(entry.summary);
  const sourcePart = entry.source ? `, ${entry.source}` : "";
  return `- [${entry.type}] ${truncatedSummary} (${entry.id}, ${entry.createdAt}${sourcePart})`;
}

/**
 * Truncate summary to max chars.
 */
function truncateSummary(summary: string): string {
  if (summary.length <= MAX_MEMORY_SUMMARY_CHARS) {
    return summary;
  }
  return summary.slice(0, MAX_MEMORY_SUMMARY_CHARS - 3) + "...";
}

// ============================================================================
// Memory Index File Operations
// ============================================================================

/**
 * Read memory index from file.
 */
export async function readMemoryIndex(filePath: string): Promise<MemoryIndexFile> {
  try {
    const content = await fs.readFile(filePath, "utf-8");
    const lines = content.split("\n");

    const entries: MemoryEntry[] = [];
    let headerLines = 0;

    // Skip header lines
    for (const line of lines) {
      if (line.startsWith("#") || line.trim() === "" || line.startsWith(">")) {
        headerLines++;
        continue;
      }
      break;
    }

    // Parse entries
    for (const line of lines.slice(headerLines)) {
      const entry = parseMemoryEntry(line);
      if (entry) {
        entries.push(entry);
      }
    }

    return {
      header: lines.slice(0, headerLines).join("\n"),
      entries,
      totalLines: lines.length,
      totalBytes: Buffer.byteLength(content, "utf-8"),
    };
  } catch {
    // Return empty index if file doesn't exist
    return {
      header: MEMORY_HEADER,
      entries: [],
      totalLines: 0,
      totalBytes: 0,
    };
  }
}

/**
 * Write memory index to file.
 */
export async function writeMemoryIndex(filePath: string, entries: MemoryEntry[]): Promise<void> {
  const content = buildMemoryIndexContent(entries);
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, "utf-8");
}

/**
 * Build memory index content from entries.
 */
export function buildMemoryIndexContent(entries: MemoryEntry[]): string {
  const lines = [MEMORY_HEADER];

  // Group by type for better readability
  const byType: Record<MemoryType, MemoryEntry[]> = {
    user: [],
    feedback: [],
    project: [],
    reference: [],
  };

  for (const entry of entries) {
    byType[entry.type].push(entry);
  }

  // Write each type section
  for (const type of MEMORY_TYPES) {
    const typeEntries = byType[type];
    if (typeEntries.length > 0) {
      lines.push(`## ${type}`);
      lines.push("");
      for (const entry of typeEntries) {
        lines.push(formatMemoryEntry(entry));
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

// ============================================================================
// Memory Index Size Checking
// ============================================================================

/**
 * Check if memory index exceeds size limits.
 */
export function checkMemoryIndexSize(content: string): {
  exceedsLines: boolean;
  exceedsBytes: boolean;
  lines: number;
  bytes: number;
} {
  const lines = content.split("\n").length;
  const bytes = Buffer.byteLength(content, "utf-8");

  return {
    exceedsLines: lines > MAX_MEMORY_INDEX_LINES,
    exceedsBytes: bytes > MAX_MEMORY_INDEX_BYTES,
    lines,
    bytes,
  };
}

/**
 * Check if entries need truncation.
 */
export function needsTruncation(entries: MemoryEntry[]): boolean {
  const content = buildMemoryIndexContent(entries);
  const sizeCheck = checkMemoryIndexSize(content);
  return sizeCheck.exceedsLines || sizeCheck.exceedsBytes;
}

// ============================================================================
// Memory Index Truncation
// ============================================================================

/**
 * Truncate memory index to fit size constraints.
 * Removes oldest entries first, keeping recent memories.
 */
export function truncateMemoryIndex(
  entries: MemoryEntry[],
  archivePath?: string,
): MemoryTruncationResult {
  const originalContent = buildMemoryIndexContent(entries);
  const originalSize = checkMemoryIndexSize(originalContent);

  if (!originalSize.exceedsLines && !originalSize.exceedsBytes) {
    return {
      truncated: false,
      linesBefore: originalSize.lines,
      linesAfter: originalSize.lines,
      bytesBefore: originalSize.bytes,
      bytesAfter: originalSize.bytes,
      entriesRemoved: 0,
    };
  }

  // Sort by creation time, keep most recent
  const sorted = [...entries].toSorted((a, b) => b.createdAt - a.createdAt);

  // Remove entries until size constraints are satisfied
  let removed: MemoryEntry[] = [];
  let kept: MemoryEntry[] = sorted;

  while (kept.length > 0) {
    const content = buildMemoryIndexContent(kept);
    const size = checkMemoryIndexSize(content);

    if (!size.exceedsLines && !size.exceedsBytes) {
      break;
    }

    // Remove oldest from kept
    const removedEntry = kept.pop();
    if (removedEntry) {
      removed.push(removedEntry);
    }
  }

  // Archive removed entries if path provided
  if (archivePath && removed.length > 0) {
    const archived = archiveRemovedEntries(removed, archivePath);
    log.info(`Archived ${removed.length} memory entries to ${archivePath}`);
    return {
      truncated: true,
      linesBefore: originalSize.lines,
      linesAfter: checkMemoryIndexSize(buildMemoryIndexContent(kept)).lines,
      bytesBefore: originalSize.bytes,
      bytesAfter: checkMemoryIndexSize(buildMemoryIndexContent(kept)).bytes,
      entriesRemoved: removed.length,
      archived,
    };
  }

  return {
    truncated: true,
    linesBefore: originalSize.lines,
    linesAfter: checkMemoryIndexSize(buildMemoryIndexContent(kept)).lines,
    bytesBefore: originalSize.bytes,
    bytesAfter: checkMemoryIndexSize(buildMemoryIndexContent(kept)).bytes,
    entriesRemoved: removed.length,
  };
}

/**
 * Archive removed entries to archive directory.
 */
function archiveRemovedEntries(entries: MemoryEntry[], archivePath: string): string[] {
  const archived: string[] = [];
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const archiveFile = path.join(archivePath, `memory-archive-${timestamp}.md`);

  const content = buildMemoryIndexContent(entries);
  const archiveDir = path.dirname(archiveFile);

  // Create archive directory if needed (fire and forget with void)
  void fs.mkdir(archiveDir, { recursive: true }).then(() => {
    fs.writeFile(archiveFile, content, "utf-8").catch((err) => {
      log.warn(
        `Failed to archive memory entries: ${err instanceof Error ? err.message : String(err)}`,
      );
    });
  });

  archived.push(archiveFile);
  return archived;
}

// ============================================================================
// Memory Entry Helpers
// ============================================================================

/**
 * Generate a unique ID for a memory entry.
 */
export function generateMemoryId(): string {
  return `mem-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Generate content hash for deduplication.
 */
export function generateContentHash(content: string): string {
  return createHash("sha256").update(content).digest("hex").slice(0, 16);
}

/**
 * Check if memory type is valid.
 */
export function isValidMemoryType(type: string): type is MemoryType {
  return MEMORY_TYPES.includes(type as MemoryType);
}

/**
 * Merge memory entries, deduplicating by content hash.
 */
export function mergeMemoryEntries(
  existing: MemoryEntry[],
  newEntries: MemoryEntry[],
): MemoryEntry[] {
  const existingHashes = new Set(existing.map((e) => e.contentHash));
  const merged = [...existing];

  for (const entry of newEntries) {
    if (!entry.contentHash || !existingHashes.has(entry.contentHash)) {
      merged.push(entry);
    }
  }

  return merged;
}
